<?
//หากมีการเรียกไฟล์นี้โดยตรง
/*if (eregi("config.in.php",$PHP_SELF)) {
    Header("Location: ../init.php");
    die();
}*/
error_reporting(E_ALL ^ E_NOTICE);
//Oracle Connect on HOST
/*
define("DB_USERNAME","EPROFILE");//oracle username
define("DB_PASSWORD","EPROFILE");// oracle password
define("DB_HOST","localhost/xe"); //ordacle host and global name
define("DB_CHARSET","AL32UTF8");//oracle character set AL32UTF8(UTF-8)
*/

//define("DB_USERNAME","SDPERSON");//oracle username
//define("DB_PASSWORD","PERSON");// oracle password
//define("DB_HOST","10.202.1.13/RSDUE2M"); //ordacle host and global name
//define("DB_CHARSET","AL32UTF8");//oracle character set AL32UTF8(UTF-8)

define("DB_USERNAME","SDPERSON");//oracle username
define("DB_PASSWORD","person");// oracle password
define("DB_HOST","10.202.1.112/RSDUE2M"); //ordacle host and global name
define("DB_CHARSET","AL32UTF8");//oracle character set AL32UTF8(UTF-8)

/*
define("DB_USERNAME","SDPERSON_DEV");//oracle username
define("DB_PASSWORD","person");// oracle password
define("DB_HOST","10.202.1.13/RSDUE2M"); //ordacle host and global name
define("DB_CHARSET","AL32UTF8");//oracle character set AL32UTF8(UTF-8)
*/
//MySQL table
define("TB_APPRAISE_TAB","SDU_APPRAISE_TAB");
define("TB_BIODATA_TAB","SDU_BIODATA_TAB");
define("TB_CEN_ADDRESS_TAB","SDU_CEN_ADDRESS_TAB");
define("TB_CERTIFICATION_TAB","SDU_CERTIFICATION");
define("TB_CHILDREN_TAB","SDU_CHILDREN_TAB");
define("TB_CONSTRUCTOR_TAB","SDU_CONSTRUCTOR_TAB ");
define("TB_CONSULT_COMMIT_TAB","SDU_CONSULT_COMMIT_TAB");
define("TB_COMMITTEE_TAB","SDU_COMMITTEE_TAB");
define("TB_CONTRACT_TAB","SDU_CONTRACT_TAB");
define("TB_CONTRACT_ISSUE","SDU_CONTRACT_ISSUE");
define("TB_CURRENT_ADDRESS_TAB","SDU_CURRENT_ADDRESS_TAB");
define("TB_CURRENT_WORK_HISTORY_TAB","SDU_CURRENT_WORK_HISTORY_TAB ");
define("TB_CURRENT_WORK_TAB","SDU_CURRENT_WORK_TAB ");
define("TB_EDUCATION_DATA","SDU_EDUCATION_DATA");
define("TB_EDUCATION_TAB","SDU_EDUCATION_TAB");
define("TB_EDUCATION_FILE_TAB","SDU_EDUCATION_FILE_TAB");
define("TB_EXTRA_SALARY_TAB","SDU_EX_SALARY");
define("TB_EXPERT_TAB","SDU_EXPERT_TAB");
define("TB_FAMILY_TAB","SDU_FAMILY_TAB");
define("TB_GUARANTEE_TAB","SDU_GUARANTEE_TAB");
define("TB_HONOR_TAB","SDU_HONOR_TAB");
define("TB_JOB_ANNOUNCEMENT_TAB","SDU_JOB_ANNOUNCEMENT_TAB");
define("TB_NAME_HISTORY","SDU_NAME_HISTORY");
define("TB_POSITION","SDU_POSITION");
define("TB_REF_ADMIN","SDU_REF_ADMIN");
define("TB_REF_BUDGET","SDU_REF_BUDGET");
define("TB_REF_DEPARTMENT","SDU_REF_DEPARTMENT");
define("TB_REF_DEPARTMENT_GROUP","SDU_REF_DEPARTMENT_GROUP");
define("TB_REF_DEPARTMENT_SUB","SDU_REF_DEPARTMENT_SUB");
define("TB_REF_EXTRA_SALARY","SDU_REF_EXTRA_SALARY");
define("TB_REF_FAC","SDU_REF_FAC");
define("TB_REF_ISCED","SDU_REF_ISCED");
define("TB_REF_LEV","SDU_REF_LEV");
define("TB_REF_NATION","SDU_REF_NATION");
define("TB_REF_POSITION","SDU_REF_POSITION");
define("TB_REF_PROGRAM","SDU_REF_PROGRAM");
define("TB_REF_TUMBON","SDU_REF_TUMBON");
define("TB_REF_AMPHUR","SDU_REF_AMPHUR");
define("TB_REF_PROVINCE","SDU_REF_PROVINCE");
define("TB_REF_RELIGION","SDU_REF_RELIGION");
define("TB_REF_SALARY_SOURCE","SDU_REF_SALARY_SOURCE");
define("TB_REF_SALARY_STEP","SDU_SALARY_STEP");
define("TB_REF_SITE","SDU_REF_SITE");
define("TB_REF_STAFFTYPE","SDU_REF_STAFFTYPE");
define("TB_REF_STAFF_LEV","SDU_REF_STAFF_LEV");
define("TB_REF_SUBSTAFFTYPE","SDU_REF_SUBSTAFFTYPE");
define("TB_REF_TIME_CONTACT","SDU_REF_TIME_CONTACT");
define("TB_REF_TRAINTYPE","SDU_REF_TRAINTYPE");
define("TB_REF_UNIV","SDU_REF_UNIV");
define("TB_REF_EXPERT","SDU_REF_EXPERT");
define("TB_REF_COURSE","SDU_REF_COURSE");
define("TB_REF_ROYAL","SDU_REF_ROYAL");
define("TB_RESEARCH_TAB","SDU_RESEARCH_TAB");
define("TB_ROYAL_TAB","SDU_ROYAL_TAB");
define("TB_SCHOLAR_CONTRACT_EX_TAB","SDU_SCHOLAR_CONTRACT_EX");
define("TB_SCH_PAY_BACK_TAB","SDU_SCH_PAY_BACK");
define("TB_SCHOLAR_TAB","SDU_SCHOLAR_TAB");
define("TB_SCHOLAR_FILE_TAB","SDU_SCHOLAR_FILE_TAB");
define("TB_SEMINAR_TAB","SDU_SEMINAR_TAB");
define("TB_USER_TAB","SDU_USER_TAB");
define("TB_VCHARKARN_ACH1_TAB","SDU_VCHARKARN_ACH1_TAB");
define("TB_VCHARKARN_ACH2_TAB","SDU_VCHARKARN_ACH2_TAB");
define("TB_VCHARKARN_ACH3_TAB","SDU_VCHARKARN_ACH3_TAB");
define("TB_VCHARKARN_ACH4_TAB","SDU_VCHARKARN_ACH4_TAB");
define("TB_VCHARKARN_ACH5_TAB","SDU_VCHARKARN_ACH5_TAB");
define("TB_VCHARKARN_ACH6_TAB","SDU_VCHARKARN_ACH6_TAB");
define("TB_VCHARKARN_POSITION_TAB","SDU_VCHARKARN_POSITION_TAB");
define("TB_POSITION_SUB_TAB","SDU_POSITION_SUB_TAB");
define("TB_WELFARE_CHILDLOAN_TAB","SDU_WELFARE_CHILDLOAN_TAB");
define("TB_WELFARE_DATAILS_TAB","SDU_WELFARE_DATAILS_TAB");
define("TB_WELFARE_TAB","SDU_WELFARE_TAB");
define("TB_WARN_PUNISH_TAB","SDU_WARN_PUNISH_TAB");
define("TB_SDU_MUNNY_TAB","SDU_MUNNY_TAB");
define("TB_SDU_PAY_FUND_TAB","SDU_PAY_FUND_TAB");

define("TB_SDU_SECTOR_TRANSFER_TAB","SDU_SECTOR_TRANSFER_TAB");
define("TB_SDU_SECTOR_TRANSFER_IMG_TAB","SDU_SECTOR_TRANSFER_IMG_TAB");
define("TB_SDU_PAY_TAB","SDU_PAY_TAB");
define("TB_SDU_FILE_MANU_TAB","SDU_FILE_MANU_TAB");
define("TB_SDU_CURRENT_WORK_H_TAB","SDU_CURRENT_WORK_H_TAB");
define("TB_WORK_HISTORY_TAB","SDU_WORK_HISTORY_TAB");
define("TB_SDU_LA_TAB","SDU_LA_TAB");
define("TB_HELP_GOV","SDU_HELP_GOV");

define("TB_SDU_DEFINE_MANAGE_TAB","SDU_DEFINE_MANAGE_TAB");
define("TB_SDU_DATA_ANSWER_TAB","SDU_DATA_ANSWER_TAB");
define("TB_SDU_CHANGE_JOB_TAB","SDU_CHANGE_JOB_TAB");
define("TB_SDU_ESTIMATE_SERVICE_TAB","SDU_ESTIMATE_SERVICE_TAB");

define("TB_SDU_BUDGET","SDU_BUDGET");
define("TB_SDU_EXPEND","SDU_EXPEND");
define("TB_SDU_BANK","SDU_BANK");
define("TB_SDU_BANK_BRANCH","SDU_BANK_BRANCH");
define("TB_SDU_BANK_PASSBOOK","SDU_BANK_PASSBOOK");
define("TB_SDU_OVERTIME","SDU_OVERTIME_PAY");
define("TB_SDU_TAXRATE","SDU_TAX_RATE");
?>
